Dedupe Linux version check

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -125,6 +125,27 @@ runs:
         Write-Output "RESOLVED_SWIFT_BUILD=$SwiftBuild" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
       shell: pwsh
 
+    - name: Validate Linux distribution
+      if: runner.os == 'Linux'
+      run: |
+        source /etc/os-release
+        echo ${ID} ${VERSION_ID}
+        case ${ID} in
+        ubuntu)
+          case ${VERSION_ID} in
+          16.04|18.04|20.04|22.04|24.04)
+            ;;
+          *)
+            echo "::error file=/etc/os-release,title=Unsupported::unsupported ${ID} release (${VERSION_ID})"
+            exit 1
+          esac
+        ;;
+        *)
+          echo ::error unknown Linux distribution
+          exit 1
+        esac
+      shell: bash
+
     - name: Generate cache key (Windows)
       if: runner.os == 'Windows' && inputs.cache == 'true'
       id: cache-key
@@ -217,21 +238,7 @@ runs:
       if: runner.os == 'Linux' && inputs.source == 'swift.org' && (inputs.cache != 'true' || steps.cache-restore.outputs.cache-hit != 'true')
       run: |
         source /etc/os-release
-        case ${ID} in
-        ubuntu)
-          case ${VERSION_ID} in
-          16.04|18.04|20.04|22.04|24.04)
-            curl -sL https://download.swift.org/${RESOLVED_SWIFT_VERSION}/ubuntu${VERSION_ID/./}/swift-${RESOLVED_SWIFT_BUILD}/swift-${RESOLVED_SWIFT_BUILD}-ubuntu${VERSION_ID}.tar.gz -o swift-toolchain.tar.gz
-          ;;
-          *)
-            echo "::error file=/etc/os-release,title=Unsupported::unsupported ${ID} release (${VERSION_ID})"
-            exit 1
-          esac
-        ;;
-        *)
-          echo ::error unknown Linux distribution
-          exit 1
-        esac
+        curl -sL https://download.swift.org/${RESOLVED_SWIFT_VERSION}/ubuntu${VERSION_ID/./}/swift-${RESOLVED_SWIFT_BUILD}/swift-${RESOLVED_SWIFT_BUILD}-ubuntu${VERSION_ID}.tar.gz -o swift-toolchain.tar.gz
       shell: bash
 
     - name: Fetch installer from swift.org (macOS)
@@ -384,25 +391,8 @@ runs:
     - name: Install Swift
       if: runner.os == 'Linux'
       run: |
-        source /etc/os-release
-        echo ${ID} ${VERSION_ID}
-        case ${ID} in
-        ubuntu)
-          case ${VERSION_ID} in
-          16.04|18.04|20.04|22.04|24.04)
-            tar zxf swift-toolchain.tar.gz -C ${HOME}
-            rm -f swift-toolchain.tar.gz
-          ;;
-          *)
-            echo "::error file=/etc/os-release,title=Unsupported::unsupported ${ID} release (${VERSION_ID})"
-            exit 1
-          esac
-        ;;
-        *)
-          echo ::error unknown Linux distribution
-          exit 1
-        esac
-
+        tar zxf swift-toolchain.tar.gz -C ${HOME}
+        rm -f swift-toolchain.tar.gz
         echo "${HOME}/usr/bin" >> $GITHUB_PATH
       shell: bash
 
